<a href="https://colab.research.google.com/github/ravishchanda/bleep/blob/Dev/intent_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Intent Classification

In [1]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.46.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.26.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2024.9.11)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.5)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.20.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.66.6)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (2024.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2024.8.30)

#import necessary libraries

In [3]:
from transformers import pipeline

In [5]:
from transformers import AutoModelForSequenceClassification, TextClassificationPipeline,AutoTokenizer

In [6]:
model_name = 'qanastek/XLMRoberta-Alexa-Intents-Classification'

In [7]:
tokenizer = AutoTokenizer.from_pretrained(model_name)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/398 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

In [8]:
model = AutoModelForSequenceClassification.from_pretrained(model_name)

config.json:   0%|          | 0.00/4.00k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

In [9]:
classifier = TextClassificationPipeline(model=model,tokenizer=tokenizer)

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

In [10]:
res = classifier("what is the weather today in Miami ?")

In [13]:
res[0]['label']

'weather_query'

In [11]:
!pip install gradio

Collecting gradio
  Downloading gradio-5.6.0-py3-none-any.whl.metadata (16 kB)
Collecting aiofiles<24.0,>=22.0 (from gradio)
  Downloading aiofiles-23.2.1-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (3.7.1)
Collecting fastapi<1.0,>=0.115.2 (from gradio)
  Downloading fastapi-0.115.5-py3-none-any.whl.metadata (27 kB)
Collecting ffmpy (from gradio)
  Downloading ffmpy-0.4.0-py3-none-any.whl.metadata (2.9 kB)
Collecting gradio-client==1.4.3 (from gradio)
  Downloading gradio_client-1.4.3-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: httpx>=0.24.1 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.27.2)
Requirement already satisfied: huggingface-hub>=0.25.1 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.26.2)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (3.1.4)
Collecting markupsafe~=2.0 (from gradio)
  Downloading MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (1.26.4)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (3.10.11)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from gradio) (24.2)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (2.2.2)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (11.0.0)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (2.9.2)
Collecting pydub (from gradio)
  Downloading pydub-0.25.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting python-multipart==0.0.12 (from gradio)
  Downloading python_multipart-0.0.12-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (6.0.2)
Collecting ruff>=0.2.2 (from gradio)
  Downloading ruff-0.8.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (25 kB)
Collecting safehttpx<1.0,>=0.1.1 (from gradio)
  Downloading safehttpx-0.1.1-py3-none-any.whl.metadata (4.1 kB)
Collecting semantic-version~=2.0 (from gradio)
  Downloading semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting starlette<1.0,>=0.40.0 (from gradio)
  Downloading starlette-0.41.3-py3-none-any.whl.metadata (6.0 kB)
Collecting tomlkit==0.12.0 (from gradio)
  Downloading tomlkit-0.12.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.13.0)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (4.12.2)
Collecting uvicorn>=0.14.0 (from gradio)
  Downloading uvicorn-0.32.1-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from gradio-client==1.4.3->gradio) (2024.10.0)
Collecting websockets<13.0,>=10.0 (from gradio-client==1.4.3->gradio)
  Downloading websockets-12.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<5.0,>=3.0->gradio) (3.10)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.10/dist-packages (from anyio<5.0,>=3.0->gradio) (1.3.1)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5.0,>=3.0->gradio) (1.2.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx>=0.24.1->gradio) (2024.8.30)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx>=0.24.1->gradio) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx>=0.24.1->gradio) (0.14.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.25.1->gradio) (3.16.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.25.1->gradio) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.25.1->gradio) (4.66.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0,>=1.0->gradio) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0,>=1.0->gradio) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0,>=1.0->gradio) (2024.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.10/dist-packages (from pydantic>=2.0->gradio) (2.23.4)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0,>=0.12->gradio) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.18.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.25.1->gradio) (3.4.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.25.1->gradio) (2.2.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.2)
Downloading gradio-5.6.0-py3-none-any.whl (57.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.1/57.1 MB 16.3 MB/s eta 0:00:00
Downloading gradio_client-1.4.3-py3-none-any.whl (320 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 320.1/320.1 kB 29.3 MB/s eta 0:00:00
Downloading python_multipart-0.0.12-py3-none-any.whl (23 kB)
Downloading tomlkit-0.12.0-py3-none-any.whl (37 kB)
Downloading aiofiles-23.2.1-py3-none-any.whl (15 kB)
Downloading fastapi-0.115.5-py3-none-any.whl (94 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.9/94.9 kB 10.7 MB/s eta 0:00:00
Downloading MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Downloading ruff-0.8.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.1/11.1 MB 109.3 MB/s eta 0:00:00
Downloading safehttpx-0.1.1-py3-none-any.whl (8.4 kB)
Downloading semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Downloading starlette-0.41.3-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.2/73.2 kB 8.1 MB/s eta 0:00:00
Downloading uvicorn-0.32.1-py3-none-any.whl (63 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.8/63.8 kB 6.5 MB/s eta 0:00:00
Downloading ffmpy-0.4.0-py3-none-any.whl (5.8 kB)
Downloading pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Downloading websockets-12.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (130 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 12.8 MB/s eta 0:00:00
Installing collected packages: pydub, websockets, uvicorn, tomlkit, semantic-version, ruff, python-multipart, markupsafe, ffmpy, aiofiles, starlette, safehttpx, gradio-client, fastapi, gradio
  Attempting uninstall: markupsafe
    Found existing installation: MarkupSafe 3.0.2
    Uninstalling MarkupSafe-3.0.2:
      Successfully uninstalled MarkupSafe-3.0.2
Successfully installed aiofiles-23.2.1 fastapi-0.115.5 ffmpy-0.4.0 gradio-5.6.0 gradio-client-1.4.3 markupsafe-2.1.5 pydub-0.25.1 python-multipart-0.0.12 ruff-0.8.0 safehttpx-0.1.1 semantic-version-2.10.0 starlette-0.41.3 tomlkit-0.12.0 uvicorn-0.32.1 websockets-12.0

In [12]:
import gradio as gr

In [14]:
def intent_classifier(text):
    res=classifier(text)
    return res[0]['label']

In [15]:
iface = gr.Interface(
    fn = intent_classifier,
    inputs = gr.Textbox(lines=2,placeholder = "Enter your query.."),
    outputs = "text",
    title = "Intent classification using HuggingFace"
)

In [16]:
iface.launch()

Running Gradio in a Colab notebook requires sharing enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://14e00d32c34e56c0d7.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

#Named Entity recognization

In [20]:
from transformers import AutoTokenizer, AutoModelForTokenClassification

In [18]:
bert_model_name = 'dslim/bert-base-NER'

In [19]:
b_tokenizer = AutoTokenizer.from_pretrained(bert_model_name)

tokenizer_config.json:   0%|          | 0.00/59.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/829 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [21]:
b_model = AutoModelForTokenClassification.from_pretrained(bert_model_name)

model.safetensors:   0%|          | 0.00/433M [00:00<?, ?B/s]

Some weights of the model checkpoint at dslim/bert-base-NER were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [22]:
b_nlp = pipeline("ner",model=b_model,tokenizer = b_tokenizer)

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

In [40]:
def bert_classifier(text):
    res=b_nlp(text)
    return res[0]['entity']

In [41]:
b_iface = gr.Interface(
    fn = bert_classifier,
    inputs = gr.Textbox(lines=2,placeholder = "Enter your query.."),
    outputs = "text",
    title = "NER using HuggingFace"
)

In [42]:
b_iface.launch()

Running Gradio in a Colab notebook requires sharing enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://17e856b9c5e7d13b1f.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

In [43]:
!pip install BERTopic

Collecting BERTopic
  Downloading bertopic-0.16.4-py3-none-any.whl.metadata (23 kB)
Collecting hdbscan>=0.8.29 (from BERTopic)
  Downloading hdbscan-0.8.40-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.10/dist-packages (from BERTopic) (1.26.4)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.10/dist-packages (from BERTopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.10/dist-packages (from BERTopic) (5.24.1)
Requirement already satisfied: scikit-learn>=0.22.2.post1 in /usr/local/lib/python3.10/dist-packages (from BERTopic) (1.5.2)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from BERTopic) (3.2.1)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.10/dist-packages (from BERTopic) (4.66.6)
Collecting umap-learn>=0.5.0 (from BERTopic)
  Downloading umap_learn-0.5.7-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.10/dist-packages (from hdbscan>=0.8.29->BERTopic) (1.13.1)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.10/dist-packages (from hdbscan>=0.8.29->BERTopic) (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.5->BERTopic) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.5->BERTopic) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.5->BERTopic) (2024.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly>=4.7.0->BERTopic) (9.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from plotly>=4.7.0->BERTopic) (24.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.22.2.post1->BERTopic) (3.5.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->BERTopic) (4.46.2)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->BERTopic) (2.5.1+cu121)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->BERTopic) (0.26.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->BERTopic) (11.0.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.10/dist-packages (from umap-learn>=0.5.0->BERTopic) (0.60.0)
Collecting pynndescent>=0.5 (from umap-learn>=0.5.0->BERTopic)
  Downloading pynndescent-0.5.13-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->BERTopic) (3.16.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->BERTopic) (2024.10.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->BERTopic) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->BERTopic) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->BERTopic) (4.12.2)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba>=0.51.2->umap-learn>=0.5.0->BERTopic) (0.43.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->BERTopic) (1.16.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->BERTopic) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->BERTopic) (3.1.4)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->BERTopic) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers>=0.4.1->BERTopic) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->BERTopic) (2024.9.11)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->BERTopic) (0.4.5)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->BERTopic) (0.20.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->BERTopic) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->BERTopic) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->BERTopic) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->BERTopic) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->BERTopic) (2024.8.30)
Downloading bertopic-0.16.4-py3-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.7/143.7 kB 9.5 MB/s eta 0:00:00
Downloading hdbscan-0.8.40-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 53.7 MB/s eta 0:00:00
Downloading umap_learn-0.5.7-py3-none-any.whl (88 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.8/88.8 kB 8.6 MB/s eta 0:00:00
Downloading pynndescent-0.5.13-py3-none-any.whl (56 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.9/56.9 kB 5.4 MB/s eta 0:00:00
Installing collected packages: pynndescent, hdbscan, umap-learn, BERTopic
Successfully installed BERTopic-0.16.4 hdbscan-0.8.40 pynndescent-0.5.13 umap-learn-0.5.7

In [44]:
from bertopic import BERTopic

In [45]:
import pandas as pd

In [46]:
df = pd.read_csv('/content/sample_data/tokyo_2020_tweets.csv')

<ipython-input-46-25e0b5d8751f>:1: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/sample_data/tokyo_2020_tweets.csv')

In [47]:
df.head()

,id,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,retweets,favorites,is_retweet
0,1418888645105356803,Abhishek Srivastav,"Udupi, India",Trying to be mediocre in many things,2021-02-01 06:33:51,45.0,39.0,293.0,False,2021-07-24 10:59:49,Let the party begin\n#Tokyo2020,['Tokyo2020'],Twitter for Android,0.0,0.0,False
1,1418888377680678918,Saikhom Mirabai Channu🇮🇳,"Manipur, India",Indian weightlifter 48 kg category. Champion🏆,2018-04-07 10:10:22,5235.0,5.0,2969.0,False,2021-07-24 10:58:45,Congratulations #Tokyo2020 https://t.co/8OFKMs...,['Tokyo2020'],Twitter for Android,0.0,0.0,False
2,1418888260886073345,Big Breaking,Global,All breaking news related to Financial Market....,2021-05-29 08:51:25,3646.0,3.0,5.0,False,2021-07-24 10:58:17,Big Breaking Now \n\nTokyo Olympic Update \n\n...,NaN,Twitter for Android,0.0,1.0,False
3,1418888172864299008,International Hockey Federation,Lausanne,Official International Hockey Federation Twitt...,2010-10-20 10:45:59,103975.0,2724.0,36554.0,True,2021-07-24 10:57:56,Q4: 🇬🇧3-1🇿🇦\n\nGreat Britain finally find a wa...,NaN,Twitter Web App,1.0,0.0,False
4,1418886894478270464,Cameron Hart,Australia,Football & Tennis Coach,2020-10-31 08:46:17,6.0,37.0,31.0,False,2021-07-24 10:52:51,All I can think of every time I watch the ring...,"['Tokyo2020', 'ArtisticGymnastics', '7Olympics...",Twitter for iPhone,0.0,0.0,False

In [52]:
docs = df[0:10000].text.to_list()

In [53]:
docs

['Let the party begin\n#Tokyo2020',
 'Congratulations #Tokyo2020 https://t.co/8OFKMs9ukq',
 "Big Breaking Now \n\nTokyo Olympic Update \n\nJapan won his first Gold 🥇 Takato Naohisa won Gold in men's 60 kg Judo, C… https://t.co/tRcfDd7clY",
 'Q4: 🇬🇧3-1🇿🇦\n\nGreat Britain finally find a way way Pieterse, with Jack Waller finding the net via the stick of a Sou… https://t.co/kdeNYg9THk',
 'All I can think of every time I watch the rings event #Tokyo2020 #ArtisticGymnastics #7Olympics #OlympicGames… https://t.co/cJaxEFnyzD',
 '#Tokyo2020 #Olympics\n#MirabaiChanu\n#Weightlifting\n\nWomen Empowerment\nREAL                         Vs… https://t.co/XLsJb2RH76',
 "Can't help but cheer for them. Banda 6 goals in 2 games. \nZambia goal difference 7-14 😄\nWell done on getting that p… https://t.co/2G8UDgMClT",
 "@inquirerdotnet @ftjochoaINQ Caloy Yulo's 14.000, however, was only good for sixth in the rings preliminaries.… https://t.co/bXPm1E0RbF",
 "Q3 🇨🇦 1-4 🇩🇪\n\nGreen card for Canada's captain Scott Tupper.\n\nFollow the Live scorecard on https://t.co/S2Zt1TJYJG\n\n#Tokyo2020 #CANvGER",
 'Hearty Congratulations to \nIndian Railways 🏋️\u200d♀️ player \nSaikhom Mirabai Chanu, for winning the first medal for Ind… https://t.co/9YW3XPLQX1',
 'GREAT FIRST ROUND ON THE RINGS!! #LabaPilipinas #TeamPhilippines #Tokyo2020 #Olympics @c_edrielzxs #TokyoOlympics',
 'Gymnastics ❤️ #Tokyo2020',
 'Morning everyone! Caffeine check! @LoriLindsey6 @LRoman32 #Tokyo2020 #TokyoOlympics https://t.co/gHtXfkQDdX',
 '5years of hardwork comes to an end for @officialvkyadav\n#VikasKrishan got defeated by\nSQM Okazawa 🇯🇵 at First round… https://t.co/aSAHeyluDe',
 '#Tokyo2020 #Tennis \n\nA win to remember for @nagalsumit, the last Indian to qualify for the Tokyo #Olympics.… https://t.co/Awsm8muQyB',
 'Proud of uhh Mirabai chanu \n#silvermedal\n#MirabaiChanu\n#Weightlifting \n#Tokyo2020 \n#TokyoOlympics \n#TeamIndia… https://t.co/wUROpvsHZe',
 'Up next for Carlos Yulo is vault. #ArtisticGymnastics #Tokyo2020 @mbsportsonline',
 'Congrates @mirabai_chanu you make our country proud🇮🇳as always🥈❣️\n@amitchhaniwala @PMOIndia @narendramodi @AmitShah… https://t.co/rNxAshDCpz',
 'Koreans are full of shit, period. \n\nRising Sun Flag\n\nhttps://t.co/zFHVDtvImr\n\n#Olympics #Tokyo2020 #OlympicGames… https://t.co/1h1yjR0gUf',
 "The wait for a weightlifting medal is over! 👏🥈\n\nMirabai Chanu opened India's medal account at #Tokyo2020, here's ho… https://t.co/fYTyoE7JOw",
 '#Tokyo2020   #MirabaiChanu  #Weightlifting  wait of 21 years ends for India, well done @mirabai_chanu  do I need to… https://t.co/wcsRFTye2K',
 '#Tokyo2020 #Olympics A very proud moment for all of use ….Jai Hind🇮🇳🇮🇳🇮🇳🇮🇳🇮🇳🇮🇳',
 'Well done to #TeamGB in the #Hockey Good game. \n#Tokyo2020',
 '#SaturdayMotivation in #Fenny\n\nAngel Rising Super Star ltd Availability so booking recommended #Today \n\n01908696569… https://t.co/ANtpb31nPH',
 'Many congratulations to #MirabaiChanu for winning India’s first medal in the ongoing #Tokyo2020 #Olympics. https://t.co/oEEh6AuiPn',
 '1’ Netherlands vs Brazil \n\nKeep a close eye on this one🔥\n\nWomen’s Summer Olympics #Tokyo2020',
 "@Reuters .@Reuters Not for Beijing and the Chinese in #Tokyo2020 ❗️❗️❗️ I'm a blogger. Tokyo: https://t.co/yjsHEBJ9B9",
 'We’re not here to take part, we’re here to take over #OlympicGames #Tokyo2020 #TeamIndia',
 'Completely agree with @Gatty54.\n\nI feel like it was a game that could have been. The pen shout and Sam’s one go in… https://t.co/2c8kA8wo12',
 'Up next for Yulo is the vault event. #Tokyo2020 #Olympics #PHI',
 "#TeamIndia  | #Tokyo2020 | #Boxing\nMen's Welter weight 63-69kg Round of 32 Results\n\nA brave @officialvkyadav bows o… https://t.co/ez0JesBLD3",
 '@FreeWestPapua #TokyoOlympics #Tokyo2020 #OlympicGames #Olympics2021 #HumanRights @UNHumanRights where are you',
 'Heartiest congratulations to #MirabaiChanu on winning the silver for  Flag of India In 49KG Weightlifting Event 🙌🙌… https://t.co/t6Ih9STY3B',
 'Piece on the volleyball action at the #Olympics on Day 1. Hosts Japan look good, Italy given a scare. #Tokyo2020 \n \nhttps://t.co/XqBzaOCILj',
 'Tokyo Olympics: IOA announces cash prize for coaches who help athletes win medals at Games\n\nRead @ANI Story |… https://t.co/kpXagK2gXv',
 "Fireworks explode as athletes gather at athletes' parade during  the opening ceremony #Tokyo2020 https://t.co/EnXMvwJlHC",
 'Come on Chan Peng Soon/Goh Liu Ying 🇲🇾 🏸\n\n#OlimpikTokyo #Tokyo2020\xa0 #DemiMalaysia',
 'Absolutely loving some the innovations in #Tokyo2020 https://t.co/imV58zKAym',
 '𝗠𝗜𝗥𝗔𝗕𝗔𝗜 𝗖𝗛𝗔𝗡𝗨!🥈👏🏻 🏋🏻\u200d♀️ \n\nAbsolutely amazing display of weightlifting.\n\nThe way you have transformed yourself after… https://t.co/ibTxtqmjGF',
 'Gymnastics on the TV and I’m happy\n\n#Tokyo2020',
 'Loved this felicitation message from @Abhinav_Bindra to @mirabai_chanu. Each sentence so powerfully motivating and… https://t.co/bgSRMaH4Lg',
 "Congratulations to @mirabai_chanu on securing India's 🇮🇳 first medal at the #Tokyo2020 as she re-wrote the history… https://t.co/wH6Rbf7C9s",
 'I went o church... Did @FAZFootball win against #China 🤔 #CHIZAM #Olympics2020 #Tokyo2020',
 '*burns all the IKEA* #SWEvAUS #Tokyo2020 https://t.co/u0AIpMqUOF',
 'Hearty congratulations to ace Indian weightlifter @mirabai_chanu for winning a Silver Medal in the women’s weightli… https://t.co/bBFOrmS0eb',
 'Driton Toni Kuka’s Olympic dream was cut short in 1991. He was 19.\nHe has in turn made our collective dream a reali… https://t.co/NPpHUal9YF',
 'Russian Olympic Committee sounds like the people at work who came up with the Olympic themed day. #Olympics #OlympicGames  #Tokyo2020',
 'YELLOW CARD - Hayashi booked for a foul on Hemp.\n\n🇯🇵 0-0 🇬🇧\n\n#Japan #TeamGB #Tokyo2020',
 'Q4: GREAT BRITAIN 3-1 SOUTH AFRICA \n\n#Hockey #Tokyo2020 #SSOlympics',
 '3x3 basketball is severely underrated imo. \n\n#Tokyo2020 #7Olympics',
 'No point of making the cut excuse either. Got completely outpunched, outboxed by a much much better boxer on the da… https://t.co/nJrsLyrbgv',
 "Here's my article for today's edition of The Scotsman on Eric Liddell, the Olympics, and my debut children's novel,… https://t.co/9DvgjcbBTF",
 'Could not have asked for a happier start to @Tokyo2020! India is elated by @mirabai_chanu’s stupendous performance.… https://t.co/RPMRGAhOdG',
 "India’s 1st medal on day 1 !\n\n@mirabai_chanu wins SILVER in women's 49kg weightlifting! 🥈🏋️\n\nIndia 🇮🇳 is so proud o… https://t.co/d51LbEWC12",
 'BRING HOME THE GOLD MEDAL!!! #PHI #Tokyo2020 #Olympics https://t.co/JnGRpZsIt9',
 "Here are the #TeamGB stars we're expecting big things from in #Tokyo2020 #Olympics https://t.co/MLameRoimy",
 "𝐎𝐅𝐅 𝐖𝐄 𝐆𝐎 😍\n\n1st medal comes home as @mirabai_chanu wins 🥈 in women's 49kg weightlifting. BFI congratulates her for… https://t.co/PbFvNtR38O",
 "How many of us saw this coming?\n\nWhat a sad end to Vikas' journey at the @Tokyo2020!\n\nHe lost 0-5!\n\n#Boxing \n#Tokyo2020 \n#Olympics",
 'Keep it up 🇲🇾🏸🔥\n#Tokyo2020\xa0 #DemiMalaysia #BadmintonMalaysia #BadmintonLovers',
 "Bit of noon footie on a Saturday, go get 'em, girls 💪 🦁🧡 @TeamNLtweets #NEDbra #TeamNL #Tokyo2020 #Olympics https://t.co/sCupGDHqTX",
 "'A little shocked:' Team USA goes without medal on opening day for first time since 1972\nhttps://t.co/5PE8yBrV51… https://t.co/bclnSB31Ec",
 'Zuri - Asmara Dior Collection - asmara_dior_collection - Spoonflower https://t.co/9HKP58gyso via @spoonflower… https://t.co/Lg40ssQd98',
 '@channel7 Please do not switch from Aussie swimming to an Italian gymnast on a pommel horse, right before our bigge… https://t.co/zfC2RvSzLV',
 'Barnaby enjoyed #rowing yesterday. #Olympics #Tokyo2020 https://t.co/GOhxECgaPU',
 "#afcb if you're looking to watch #Tokyo2020\nCheckout eurosport channels 983 to 989 on the Sky box for wider coverage",
 "Caloy Yulo's 14.000, however, was only good for sixth in the rings preliminaries. #Tokyo2020 #InquirerXOlympics https://t.co/BTC6IKZyqx",
 "Complete Schedule for Indian Women's and Men's Hockey matches at #Tokyo2020. Do save the dates and don't miss out o… https://t.co/PfrMJqMlXw",
 '#Tokyo2020 \n\nWhere’s porridge? https://t.co/8vsfSg85jZ',
 '.@SAILsteel joins the Nation in congratulating @mirabai_chanu for becoming the 1st Indian weightlifter to win silve… https://t.co/gtd9h8KcSv',
 'This is one I’m really excited for #NEDvBRA #Olympics #Tokyo2020',
 'Congratulations @mirabai_chanu for winning a SILVER Medal in the women’s weightlifting event at the 2020 Tokyo… https://t.co/NnnuWgmPlr',
 'Indian cricket fraternity hails Mirabai Chanu for the Silver medal at Olympics 2020.\n\n#MirabaiChanu #Cheer4India… https://t.co/qznQt918Ps',
 'Heartiest congratulations to @mirabai_chanu for winning the first medal for India.\n\n#Cheer4India #Olympics… https://t.co/zAJDkbw6S8',
 "Men's 400m Individual Freestyle Heat 2 #Swimming  #Tokyo2020 #TokyoOlympics #Tokyo2021 #Olympics  #OlympicGames… https://t.co/rIG2a1RTUg",
 'Today, Bunshun magazine reveals the details of the original plans for Tokyo2020 opening ceremony by Mikiko.… https://t.co/O8X7dggYst',
 'Caloy Yulo on the steel rings. He sticks his landing! #Tokyo2020 #SeeUsStonger @CignalTV @OneSportsPHL https://t.co/8hIwmWwg63',
 'Here we go! This should be a fun one!  #NEDvBRA #Tokyo2020',
 'No Nigerian representation for football events for both male and female category in the Olympics \n\nShows how much r… https://t.co/66lrFfJrRu',
 "In case you missed it...\n\nJudoka Takato wins hosts Japan's first gold medal of Tokyo 2020\n\nhttps://t.co/KAxi4W0g0t\n\n#Tokyo2020",
 "Q3 🇨🇦 1-4 🇩🇪\n\nChristopher Rühr's shot on goal is again brilliantly saved by Frederik van Son!\n\nFollow the Live scor… https://t.co/7JOdeis3K4",
 "Fireworks explode as athletes gather at athletes' parade during  the opening ceremony #Tokyo2020 https://t.co/yGQtkMMLiG",
 'Congratulations to\n@mirabai_chanu\n  on winning the Silver Medal at \n@Tokyo2020\n #TokyoOlympics2020 \n #Tokyo2020… https://t.co/hScV5be5p7',
 'Congratulations Mirabai Chanu for winning India the first medal, that too silver in the Tokyo Olympics.… https://t.co/qWi6u7Ly6E',
 '#Olympics #OlympicGames #Tokyo2020  Kenya vs Mongolia  boxing going on now.',
 'Rectangle Switzerland flag is a crime. #Tokyo2020',
 'BREAKING : Vikas Krishan loses 0-5 to Sewonrets Quincy Mensah Okazawa of Japan in Round of 32 bout of 69kg event… https://t.co/diZ1zILMV1',
 'Go Caloy! Bring home that first Olympic Gold medal for PH! #Tokyo2020 #TokyoOlympics2021',
 "Big Breaking Now \n\nTokyo Olympic Update \n\nJapan won his first Gold 🥇 Takato Naohisa won Gold in men's 60 kg Judo, C… https://t.co/ND0hXSiZdh",
 '@Troll65264734 @Olympics @visheprasad With his talent Vikas could have easily won it \n#Boxing\xa0 #Tokyo2020\xa0… https://t.co/8rAkpmAiLs',
 'World No. 1 mixed doubles #Zheng Siwei/Huang Yaqiong brushed aside their Egyptian opponents in #Tokyo2020… https://t.co/sDhvZlLMQX',
 "Oh there's men's #volleyball on my screen! Finally #Tokyo2020",
 'Remedy Rule fails to make it to the semifinals as she places 25th out of the 34 competitors.\n\n#PHI #Tokyo2020… https://t.co/YmBTln6Iue',
 'Come on girls! #NED #BRA #NEDBRA #Tokyo2020',
 'Our Goodwill Ambassador @YusraMardini gave a powerful performance in the Women’s 100m Butterfly at #Tokyo2020… https://t.co/rKJBAI07Bo',
 'Adam Peaty - destined for another Olympic gold? 🥇\n\nThe Team GB swimmer gets his #Tokyo2020 campaign up and running… https://t.co/fYwCxCofJm',
 'FT: Chile 🇨🇱 1-2 Canada 🇨🇦 \n\n✌️Beckie’s double was enough to give #TeamCanada a massive step towards qualification… https://t.co/q9217jXOTO',
 'Congratulations @mirabai_chanu on winning silver at #Tokyo2020 🇮🇳 https://t.co/GubVD4OeiP',
 'Nice one @c_edrielzxs 💖\n\n#Tokyo2020',
 'Awake and ready for the 4x100 Freestyle Relay ……. #Swimming #TeamUSA #Tokyo2020 let’s GO. https://t.co/qeEqBmglTX',
 'So proud momento só com o pé directed her opening to Tokyo2020\xa0 #Olympics edition. This Junmyeon… OLYMPIC CHAMPION,… https://t.co/Uj5tZjH6wI',
 "It's a huge upset for  #TeamIndia as Vikas Krishan is eliminated in first round itself in #Boxing at #Tokyo2020… https://t.co/Tz6zRMXSSt",
 'Watch the Turkish men finish top 8 as a group of individuals #Tokyo2020',
 'lets gooooo #Tokyo2020',
 '𝗠𝗜𝗥𝗔𝗕𝗔𝗜 𝗖𝗛𝗔𝗡𝗨!🥈👏🏻 🏋🏻\u200d♀️ \n\nThe way you have transformed yourself after your injury and clinched a historic silver fo… https://t.co/2LJaOxyWBq',
 'I Am Really Happy For First Medal In Silver Medal 🏅 @mirabai_chanu Proud Moment Today🤩 #IndiaAtTokyo2020 #Tokyo2020… https://t.co/RiDfCFiW9s',
 '@ThumsUpOfficial Cheers and joy can make even the tensest situation a positive and light one….. As a team, let us a… https://t.co/uZ7ZgaKyv9',
 "India strikes first medal at Olympic #Tokyo2020 ! Mirabai Chanu wins silver Medal in 49 kg Women's Weightlifting an… https://t.co/94Xx04Pews",
 "We are still proud of you Vikas. You'll win some, you'll lose some. Don't worry.. there's always a next time♥️💪🏽\n#Boxing #Tokyo2020",
 'Whole nation proud of u @mirabai_chanu , The way you have transformed yourself after your injury and clinched a his… https://t.co/ansVYVJ193',
 'Comeback….. \n\n#Badminton\xa0 \n#Tokyo2020\xa0 \n#OlympicGames',
 'Q4: 🇬🇧3-1🇿🇦\n\nGreat Britain finally find a way past Pieterse, with Jack Waller finding the net via the stick of a So… https://t.co/jVuS140fJM',
 'Absolutely amazing bigg congrats @mirabai_chanu #MeerabaiChanu \n#Weightlifting \n#Tokyo2020 \n#TeamIndia https://t.co/3jscY6GheU',
 'Also, does anyone else find themselves supporting people because they come from countries which have won very few O… https://t.co/Z6Mgd8J8fh',
 'Barbara Banda | Zambia 🇿🇲\n● Scored back to back  Hat tricks \n● First Woman to do that for National Team \n\nSuch wome… https://t.co/ybkOP5msVi',
 'My favorite thing about the Olympics is we get home from being out all night &amp; they up getting to it!!! 💪 #Tokyo2020',
 "@inquirerdotnet @ftjochoaINQ Caloy Yulo's 14.000, however, put him sixth in rings in the preliminaries. #Tokyo2020… https://t.co/2A9iMbFw1M",
 '#TeamGB are finding this game pretty tough going against a very energetic #JPN side. I wonder if it’s the lack of w… https://t.co/8uCkDarGmV',
 "Adam Peaty had fear of water from brothers' shark torment and screamed in bath #Tokyo2020\nhttps://t.co/juWqzkhMfB https://t.co/O9fPNLF8dw",
 '#TeamCanada at the  #Tokyo2020 #Olympics #CAN\n\n#swimming 🏊\u200d♀️ \n\n100 metre Butterfly women ♀️ \n\nWorld champ Maggie M… https://t.co/ZlVoCL02s0',
 'Congrats! More #medals have been won at #Tokyo2020. \nTweet automatically posted when more medals are won in… https://t.co/xhO4hUkXBF',
 'Omg I found Oozara Subaru and her relatives \n\n#Vtuber #VTuberEN #Tokyo2020 #VTuberUprising #ENVtuber #ENVtuber… https://t.co/tfYhoCrczi',
 'Congratulations to @LindseyHoran who is set to earn her 100th @USWNT cap at #Tokyo2020\n\n@TeamUSA face @TheNZTeam in… https://t.co/YfTdtkPJad',
 'Mestre! M400 free style🇻🇪 #Tokyo2020',
 'stories #Cgm48Official #CGM48_stories \n\nhash tag:\n #teamthailand\n #unitedbyemotion\n #strongertogether\n #cgm48… https://t.co/VcpEIzepx8',
 'Team Kenya Athletes fly out to Tokyo ahead of Olympic Games\n#teamkenya #tokyo2020 https://t.co/dWLY0XMhQP',
 'Knee and back injuries are common in martial arts like judo and taekwando, due to quick changes in direction, twist… https://t.co/r06f0rXdyu',
 "Game Started: Netherlands v Brazil, Netherlands v Brazil, Olympic Women's Tournament Tokyo 2020,… https://t.co/4ZkRp6EPDO",
 'Congratulations @mirabai_chanu 🇮🇳 on wining the Silver for #TeamIndia in #Weightlifting\n#MirabaiChanu\n#Tokyo2020… https://t.co/5SzaAd6Czx',
 'Andy Murray advances in men’s doubles as tennis players suffer in Tokyo heat | By @tumcarayol\n#Tokyo2020 https://t.co/RqKmQkLmY2',
 "We're all behind Team GB 🇬🇧\nGet your very own timeless @BenshermanUK piece with us online or in stores. Commemorati… https://t.co/qVWpYw11HG",
 'Now watching #Tokyo2020 Men’s #volleyball  Poland v Iran',
 'Less than a week to go now... \n\n#Tokyo2020 #Olympics #Athletics https://t.co/aUC5LE8HpL',
 "Who doesn't love drones?! #Tokyo2020 🌍 https://t.co/Iu98ymqUqd",
 'Piroz be!\n\n#Tokyo2020\nİstanbul #Ayasofya',
 'Shey this 2 useless stations will not show matches niii.  I wan watch Netherlands vs Brazil na.  #Tokyo2020',
 'I have just started watching the #Tokyo2020 Opening Ceremony. Olympic opening ceremonies always give me the goosebu… https://t.co/1M4zDIyyGc',
 'ConCongratulations #MirabaiChanu on winning Silver medal for the country!🇮🇳🥈\nYou have made us all proud 🙌🏻… https://t.co/f80ayojBzZ',
 'Congratulations #MirabaiChanu on winning Silver medal for the country!🇮🇳 proud of you \n#Cheers4India #Tokyo2020… https://t.co/AXXIYgsqES',
 'I love this GB kit ⚽️🔥\n\n#Tokyo2020',
 "#IndiaTodayAtOlympics: @mirabai_chanu's father says he's proud of his daughter for making India proud. Listen in.… https://t.co/PuLcul4EyE",
 'Congratulations @mirabai_chanu for winning a hard earned and well deserved Silver Medal .🇮🇳\n#Tokyo2020 https://t.co/qFK8WMPv9I',
 'Our hope for #Tokyo2020 medals  are chasing keke and yellow-bus in +30°C in Lagos traffic etc. Boxing fall-of-famer… https://t.co/6uWYpvZJ16',
 "Get your act together @SonyLIV Don't spoil the Olympics experience for us. Your coverage is pretty bad so far #Tokyo2020",
 'Russia 🇷🇺 vs USA 🇺🇸 men’s tennis doubles match was absolutely insane WOW 🔥🔥 #Olympics #Tokyo2020 @FTiafoe #USA',
 '#Badminton so fun to watch, they going crazy #Tokyo2020',
 'Day one in the books #Tokyo2020 \nMount Fuji 🗻 showed itself at the end of the day 🚴🏻\u200d♂️🚴🏽🚴🏾\u200d♂️ #beattheheat… https://t.co/09XdtSzktS',
 'Hello #couchpeloton The cycling feed in the USA has two Australian commentators- male and female. #Tokyo2020 Any cl… https://t.co/TwJ1ffBEE5',
 ". @BBCSport .@TeamGB\n .@britishswimming\nWhy are we not getting the swimming live from #Tokyo2020 it's not even on r… https://t.co/51OsbqSkvx",
 '#Tokyo2020 \nTaekwondo\nQuarterfinals\n\nDEMSE Solomon of #Ethiopia lost against JENDOUBI Mohamed Khalil',
 'Great first swim by @walsheellen right on her best time. Huge congratulations! Looking forward to the 200 IM now. #Tokyo2020 #TeamIreland',
 "#TeamIndia  | #Tokyo2020| #Boxing \nUnfortunately #VikasKishanYadav  loses to Japanese Boxer.\nBut it's okay we will… https://t.co/TDLk1Gzg9I",
 "Subdivision 3 of the Artistic Gymnastics Men's Qualification tournaments starts now. Carlos Yulo 🇵🇭 will compete in… https://t.co/7A57byVoVa",
 'What a super feat! Congratulations #MirabaiChanu . Salute to your commitment, journey and this moment of glory 👏🏼💫… https://t.co/DgdsT7ZjH1',
 "let's go guys #Tokyo2020 #Handball",
 'Which idiot at @SonyLIV thought that swimming is not a category worth to be shown live? What kind of coverage is th… https://t.co/DtkI3WRIZ0',
 "Harmanpreet Singh's Brace Helps Indian Men's Hockey Team Edge Past New Zealand In Olympics Opener.… https://t.co/oTplDAk1tA",
 'Hello PH Govt, media #Olympics #Tokyo2020 https://t.co/CySeJKIbpI',
 '@ThumsUpOfficial @realmanubhaker India is ready to rock in #Tokyo2020',
 '#Tokyo2020 \n#TokyoOlympics2021 \n@PMOIndia \n@ianuragthakur \nMany many Congratulations... https://t.co/MUt7Ev4Yse',
 'Saurabh Chaudhary (@SChaudhary2002 ) made India’s first final of the #Tokyo2020 Olympics Shooting competition, fini… https://t.co/rQ4zHPS6MQ',
 'Concentration + satisfaction - Ibrahim Colak 🇹🇷 #Tokyo2020 #ArtisticGymnastics https://t.co/J6itbzNgmI',
 'Huge congratulations to #MirabaiChanu on winning the silver for weightlifting at the #Tokyo2020 Olympics. The actio… https://t.co/aqVqWO7Mqm',
 'Congratulations Proud feel India❤️🇮🇳💪@mirabai_chanu \n#ind #Tokyo2020 #Cheer4India #SupportSmallStreamers… https://t.co/SPJWqNXRdP',
 '➡️Could not have asked for a happier start to Tokyo 2020! India is elated by Mirabai Chanu’s stupendous performance… https://t.co/xLLRIKbP2q',
 'Thanks, topics\n#Tokyo2020 https://t.co/I9PZYauCNP',

In [54]:
model = BERTopic(verbose = True)

In [55]:
model.fit(docs)

2024-11-26 03:19:58,850 - BERTopic - Embedding - Transforming documents to embeddings.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/313 [00:00<?, ?it/s]

2024-11-26 03:20:10,228 - BERTopic - Embedding - Completed ✓
2024-11-26 03:20:10,230 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-11-26 03:21:00,002 - BERTopic - Dimensionality - Completed ✓
2024-11-26 03:21:00,007 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-11-26 03:21:00,676 - BERTopic - Cluster - Completed ✓
2024-11-26 03:21:00,690 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-11-26 03:21:01,354 - BERTopic - Representation - Completed ✓

In [56]:
model.get_topic_freq().head(10)

     Topic  Count
8       -1   2683
4        0    505
11       1    470
6        2    402
149      3    287
83       4    215
0        5    202
13       6    197
10       7    186
29       8    133

In [57]:
model.get_topic(2)

[('banda', 0.060895004091015226),
 ('zambia', 0.05383673227151453),
 ('barbra', 0.041139413567419486),
 ('china', 0.0356932783687926),
 ('barbara', 0.027212190057942266),
 ('hattricks', 0.020868844774256184),
 ('hattrick', 0.019117064632207897),
 ('44', 0.018618862990700927),
 ('goals', 0.018413624904283797),
 ('two', 0.01660038263554662)]

In [58]:
model.visualize_topics()

/usr/local/lib/python3.10/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

In [59]:
model.visualize_barchart()